# Generated by Django 4.2.16 on 2024-11-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimos.aluno'),
        ),
    ]
